### ISSUE TITLE
Pegar o Graphql server

### ISSUE THREAD

**Issue by Gutyerrez** [andreroggeri/pynubank#227]
Não é mais possível pegar o ghostflame? // tb tentei usar o pynubank mas da erro de None qnd tenta requisitar o balance da conta

Únicos links que retornaram aqui:

![image](https://user-images.githubusercontent.com/36475012/115820601-8afc0380-a3d7-11eb-94e9-a0e48a1c9738.png)

**Comment by andreroggeri** [comment]
Fiz teste aqui e está funcionando com a minha conta, tem um código de exemplo pra compartilhar ?

E vc está conseguindo logar pelo app ou site ?

**Comment by Gutyerrez** [comment]
> Fiz teste aqui e está funcionando com a minha conta, tem um código de exemplo pra compartilhar ?
> 
> E vc está conseguindo logar pelo app ou site ?

Então, eu to testando com uma conta pessoal, tem que ser obrigatoriamente uma conta PJ?

Não estou usando código, apenas o insomnia e sim, estou conseguindo logar pelo app (pelo site não)

**Comment by andreroggeri** [comment]
Não, é com conta normal (Pessoa fisica).

Vc comentou que com o pynubank tb deu erro, talvez se vc mostrar o código eu consiga te ajudar.

**Comment by Gutyerrez** [comment]
> Não, é com conta normal (Pessoa fisica).
> 
> Vc comentou que com o pynubank tb deu erro, talvez se vc mostrar o código eu consiga te ajudar.

Esse foi o código que usei pra testar:

```
from pynubank import Nubank

nu = Nubank()

nu._password_auth(
  '706XXXXXX93',
  'XXXXXXXXXXXXXXXXXXXXX'
)

print(nu.get_account_balance())
```

O output que recebi:

```
PS C:\Users\Gutye\Documents\Rede Fantasy\nubank-test> py index.py
Traceback (most recent call last):
  File "C:\Users\Gutye\Documents\Rede Fantasy\nubank-test\index.py", line 10, in <module>
    print(nu.get_account_balance())
  File "C:\Users\Gutye\AppData\Roaming\Python\Python39\site-packages\pynubank\nubank.py", line 160, in get_account_balance   
    data = self._make_graphql_request('account_balance')
  File "C:\Users\Gutye\AppData\Roaming\Python\Python39\site-packages\pynubank\nubank.py", line 38, in _make_graphql_request  
    return self._client.post(self._query_url,
  File "C:\Users\Gutye\AppData\Roaming\Python\Python39\site-packages\pynubank\utils\http.py", line 46, in post
    return self._handle_response(post(url, json=json, headers=self._headers, **self._cert_args))
  File "C:\Python39\lib\site-packages\requests_pkcs12.py", line 148, in post
    return request('post', *args, **kwargs)
  File "C:\Python39\lib\site-packages\requests_pkcs12.py", line 117, in request
    return request_orig(*args, **kwargs)
  File "C:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Python39\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Python39\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

**Comment by andreroggeri** [comment]
Esse código não vai funcionar mesmo pq está chamando os métodos privados.

Na parte de autenticação recomendo dar uma olhada nos [exemplos](https://github.com/andreroggeri/pynubank/tree/master/examples)
