### ISSUE TITLE
get_bill_details() KeyError: 'self'

### ISSUE THREAD

**Issue by fe2516** [andreroggeri/pynubank#252]
```
# Lista de dicionários contendo todas as faturas do seu cartão de crédito
bills = nu.get_bills()
print(bills)
```

```
# Retorna um dicionário contendo os detalhes de uma fatura retornada por get_bills()
bill_details = nu.get_bill_details(bills[1])
print(bill_details)
```

O primeiro bloco retorna as faturas, mas o segundo bloco dá erro:

```
Traceback (most recent call last):
  File "/Users/fao/projects/python/meuofxnubank/main.py", line 22, in <module>
    bill_details = nu.get_bill_details(bills[1])
  File "/Users/fao/.virtualenvs/meuofxnubank/lib/python3.9/site-packages/pynubank/nubank.py", line 156, in get_bill_details
    return self._client.get(bill['_links']['self']['href'])
KeyError: 'self'
```

**Comment by andreroggeri** [comment]
Você pode colocar o código completo aqui ? 

Rodei o exemplo abaixo e ele deu certo

```
if __name__ == '__main__':
    nu = Nubank()
    nu.authenticate_with_cert(CPF, PASSWORD, CERT_PATH)

    bills = nu.get_bills()
    print(bills)

    bill_details = nu.get_bill_details(bills[0])
    print(bill_details)
```

**Comment by fe2516** [comment]
```
from pynubank import Nubank

nu = Nubank()
nu.authenticate_with_cert(CPF, SENHA, 'cert.p12')

card_statements = nu.get_card_statements()

print(sum([t['amount'] for t in card_statements]))     # funciona

bills = nu.get_bills()
print(bills).     # funciona

# Retorna um dicionário contendo os detalhes de uma fatura retornada por get_bills()
bill_details = nu.get_bill_details(bills[2])     # dá o erro indicado acima.
print(bill_details)

```

**Comment by tavlima** [comment]
@andreroggeri, tenta chamar o `get_bill_details` passando uma fatura cujo `state` seja `'future'` e você vai ver o problema.

**Comment by tavlima** [comment]
Isso é relacionado a https://github.com/andreroggeri/pynubank/issues/112. Faturas com `state = (open|overdue)` funcionam bem, mas `future` não. Pelo que vi, a API do `get_bills` n retorna `links: {}` para faturas futuras.

**Comment by andreroggeri** [comment]
Eu não tenho nenhuma fatura aberta para testar, mas nesse caso não vejo
muito o que fazer.

Em sáb., 24 de set. de 2022 04:00, Thiago Lima ***@***.***>
escreveu:

**Comment by tavlima** [comment]
Me pergunto como o webapp faz... Tentei fazer inspect nos requests, mas não entendo bem como o proxy do Nubank funciona, tampouco o encoding feito do payload. Alguma sugestão?
