### ISSUE TITLE
Erro no fluxo de "Autenticando com QR Code"

### ISSUE THREAD

**Issue by Peridian** [andreroggeri/pynubank#45]
Fui tentar usar a lib e deu o erro abaixo

A única diferença do código do README foram o meu cpf , senha de acesso e o argumento "_allow_qr_code_auth=True_"

O problema parece estar no print no terminal dos caracteres que compõe o QRCode de autenticação

Peguei pra mexer na lib pela primeira vez agora, então não é impossível que eu esteja deixando algo passar desapercebido...

Segue stacktrace:
------------------
You must authenticate with your phone to be able to access your data.
Scan the QRCode below with you Nubank application on the following menu:
Nu(Seu Nome) > Perfil > Acesso pelo site
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pynubank\utils.py", line 8, in print_qr_code
    get_ipython
NameError: name 'get_ipython' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "min.py", line 6, in <module>
    allow_qr_code_auth=True
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pynubank\nubank.py", line 33, in __init__
    self.authenticate(cpf, password)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pynubank\nubank.py", line 102, in authenticate
    self._qr_code_auth()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pynubank\nubank.py", line 64, in _qr_code_auth
    utils.print_qr_code(str(content))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pynubank\utils.py", line 12, in print_qr_code
    qr.print_ascii(invert=True)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\qrcode\main.py", line 267, in print_ascii
    out.write(codes[pos])
  File "C:\Program Files (x86)\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 0: character maps to <undefined>

**Comment by andreroggeri** [comment]
Consegue testar com a versão da master?

pip install git+https://github.com/andreroggeri/pynubank.git@master

Em qua, 1 de mai de 2019 18:24, Tuca <notifications@github.com> escreveu:

**Comment by Peridian** [comment]
Rodei o primeiro código logo abaixo de **NuConta** e foi!

Sabe dizer onde estava o problema?

**Comment by andreroggeri** [comment]
Ótimo ! 😄 

Tinha uma lógica pra saber se estava rodando no Jupyter ou não.
Pelo o seu stacktrace parece que estava dando erro nessa parte.

Outra coisa, tenta logar sem o QRCode, nessa implementação eu achei um "furo" que ainda dá pra logar só com CPF/Senha.
