### ISSUE TITLE
Problema com authenticate_with_qr_code

### ISSUE THREAD

**Issue by decarvalhohenrique** [andreroggeri/pynubank#69]
Acabei de conhecer a lib.
Tentei rodar o programa pelo console, mas encontro o seguinte erro:

```
>>> from nubank import *
>>> nu = Nubank()
>>> uuid, qr_code = nu.get_qr_code()
>>> qr_code.print_ascii(invert=True)
█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ ██▄▀ █ ▀ ▀▀▄▄▄█ ▄▄▄▄▄ ████
████ █   █ █ ▀▀ ▄▄▀ ▀▀ ▄ █ █   █ ████
████ █▄▄▄█ █ ▀▄ ███▀█▄▄▄▀█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █ █ █ █ █▄█ █▄▄▄▄▄▄▄████
████ █   ▄▄██████▀▀▄▄▄▀▀▄█ ▄  ▄█▀████
████▄▄ █▄▀▄▄█▄ ██ ▄▄█▄ ██▀█  █▄ █████
████▀▀▄▀ ▀▄▀▄█▀█▀█▄▄▀▄▄ ▄ ▀▄▀▄▄▀▀████
████▄█▀  ▀▄█▄█▀█ █▀ ██ █ █▄▄▀▀▄▀▀████
████▀▀▄▄  ▄█ █▄█▄▀▀█▄▄▀ █▄▀▀▀█▄▀▀████
████ ██ ▀█▄▄▀ ▀▀▄ ▄▄▄█▀▀▀▀█  █▄██████
████▄██▄▄█▄▄ ▄█  █▄▄▄▄▀█ ▄▄▄  ▄▄▀████
████ ▄▄▄▄▄ █▀█▄█▄█▀ █▄   █▄█ ▄█ █████
████ █   █ █  █▀▄█▀█▄ ▄█ ▄▄ ▄▄▄▀▀████
████ █▄▄▄█ █▄▄▀   ▀  █▄ ▀ ▄▀ ▄▄ █████
████▄▄▄▄▄▄▄█▄█▄███▄▄▄▄▄███▄▄██▄██████
█████████████████████████████████████
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
>>> nu.authenticate_with_qr_code('CPF', 'SENHA', uuid)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/henriquecarvalho/github-repos/pynubank/pynubank/nubank.py", line 113, in authenticate_with_qr_code
    self.refresh_token = auth_data['refresh_token']
KeyError: 'refresh_token'
```
É algum problema com a informação enviada pelo Nubank?

(Enquanto estamos em uma issue, acho que a versão do pip está desatualizada)

**Comment by andreroggeri** [comment]
@decarvalhohenrique  Removi a funcionalidade de autenticação por refresh_token e estou publicando a 1.0.0 com essas alterações
