### ISSUE TITLE
NuException does not show which status code I actually got

### ISSUE THREAD

**Issue by caarlos0** [andreroggeri/pynubank#80]
exception looks like this:

```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    nu.authenticate_with_qr_code(os.environ['NU_CPF'], os.environ['NU_PWD'], uuid)
  File "/usr/local/lib/python3.8/site-packages/pynubank/nubank.py", line 96, in authenticate_with_qr_code
    auth_data = self._password_auth(cpf, password)
  File "/usr/local/lib/python3.8/site-packages/pynubank/nubank.py", line 79, in _password_auth
    data = self._handle_response(response)
  File "/usr/local/lib/python3.8/site-packages/pynubank/nubank.py", line 84, in _handle_response
    raise NuException(f'The request made failed with HTTP status code {response.status_code}',
pynubank.nubank.NuException
make: *** [run] Error 1
```

its probably a 422, but I think it should show it here...

**Comment by andreroggeri** [comment]
Yeah, I think this will be solved by #79
