### ISSUE TITLE
pynubank.nubank.NuException: The request made failed with HTTP status code 403

### ISSUE THREAD

**Issue by ricardochaves** [andreroggeri/pynubank#86]
```python
from pynubank import Nubank

uuid, qr_code = nu.get_qr_code()

qr_code.print_ascii(invert=True)

# O QRCode foi devidamente exibido e lido pelo app

nu.authenticate_with_qr_code('CPF', 'SENHA', uuid)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ricardochaves/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pynubank/nubank.py", line 94, in authenticate_with_qr_code
    auth_data = self._password_auth(cpf, password)
  File "/Users/ricardochaves/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pynubank/nubank.py", line 78, in _password_auth
    data = self._handle_response(response)
  File "/Users/ricardochaves/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pynubank/nubank.py", line 83, in _handle_response
    raise NuException(response.status_code, response.json(), response.url)
pynubank.nubank.NuException: The request made failed with HTTP status code 403

```

Fiz o mesmo teste sem a linha `qr_code.print_ascii(invert=True)` e recebi o 401, logo entendo que o QRCode fez passar o 401 e agora foi para um 403.

O CPF e Senha estão corretos, por isso quando eu olho para o erro nessa função `_password_auth` eu fique sem conseguir avançar na investigação.

Estou agora fazendo uma investigação no site deles para tentar entender quais URLs devem ser usadas.

**Comment by andreroggeri** [comment]
Consegue capturar a exceção e mandar aqui o atributo `response`?

**Comment by ricardochaves** [comment]
@andreroggeri , fiz o clone e rodei o projeto referenciando direto seu código para fazer o debug, rodou normalmente e funcionou... não sei o que eu fiz de errado antes, vou usar dessa forma mesmo. Obrigado.
